import Head from 'next/head';
import Image from "next/image";
import Table from "react-bootstrap/Table";
import Link from 'next/link'
import React, {useState, useEffect} from 'react';


   
  
export default function Home() {
   useEffect(() => {
    //  let checkedAll = document.getElementById("checkAll");
    //  let checkboxes = document.querySelectorAll("input[type = checkbox]");

    //  checkedAll.addEventListener("click", function() {
    //    checkbox.checked = false;
    //    if ((checkedAll.checked = true)) {
    //      checkboxes.forEach(checkbox=> {
    //        checkbox.checked = true
    //      })
    //    }

      
    //  })

   });


  return (
    <div>
      <Head>
        <title>Sticky Add to Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>

      <main style={{ padding: 30 + "px" }}>
        <div className="container-1">
          <div className="container-child-one">
            <h1>Statistics</h1>
            <p>
              Display sticky add to cart anywhere on your product pages, allow
              customer to choose variants & purchase, without having to scroll
              up to the Add To Cart button to choose variants and proceed to
              checkout.
            </p>

            <div className="dropdown-div">
              <select
                className="form-select my-select shadow-none bg-light"
                aria-label="Default select example"
                id="dashBoardSelect"
              >
                <option defaultValue>Sticky Widget</option>
                <option value="1">Sticky cart</option>
                <option value="2">Sticky cart preview</option>
                <option value="3">Quick buy widget</option>
                <option value="1">Sticky URL button</option>
                <option value="2">Remember my cart</option>
                <option value="3">Festival attraction</option>
              </select>
              <Link href="/button/create">
               <a> <button type="button" className="btn create-btn shadow-none">
                  Create
                </button></a>
              </Link>
              {/* <Link href="/button/:id">
              <a> <button type="button" className="btn create-btn shadow-none">
                  Save
                </button></a>
              </Link> */}
             
            </div>
          </div>

          <div className="container-child-two bg-light">
            <div>
              <h3>Small Analytics</h3>
              <Image
                src="/assets/eye.svg"
                alt="eye"
                width={18}
                height={14}
                className="eye"
              />
            </div>

            <div className="analytics-content">
              <div>
                <span id="totalClicks">234</span>
                Total Clicks
              </div>
              <div>
                <span id="remainingClicks">876</span>
                Remaining Clicks
              </div>
              <div>
                <span id="myWidgets">11</span>
                My Widgets
              </div>
            </div>
          </div>
        </div>

        <div className="container-2">
          <h3>Small Analytics</h3>
          <div className="chart-content">
            <div>
              Widget status: <span id="widgetStatus"> Turned on </span>
            </div>
            <div>
              Sort by: <span id="sortBy"> Names </span>
            </div>
            <div>
              Plot twist: <span id="plotTwist"> Names </span>
            </div>
          </div>

          <Table borderless responsive className="table table-one">
            <thead>
              <tr className="table-head align-middle bg-light">
                <th scope="col">
                  <input type="checkbox" id="checkedAll" />
                </th>

                <th scope="col">Number</th>
                <th scope="col">Name</th>
                <th scope="col">Location</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>
                <th scope="col">Clicks</th>
                <th scope="col">Data Created</th>
                <th scope="col">
                  <Image
                    src="/assets/dots-vertical.svg"
                    alt="dots"
                    width={12}
                    height={18}
                   
                    className="dotz"
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="align-middle">
                <th scope="row" className="table-border-custom">
                  <input type="checkbox"></input>
                </th>
                <td id="tableItemNumber">1</td>
                <td id="tableItemName">Sticky Widget</td>
                <td id="tableItemLocation">All over Web</td>
                <td id="tableItemDescription">My new button</td>
                <td id="tableItemStatus" className="status">
                  ON
                </td>
                <td id="tableItemClicks" style={{ fontWeight: 900 }}>
                  124556
                </td>
                <td id="tableItemDataCreated">23/11/2020</td>
                <td>
                  <Image
                    src="/assets/dots-vertical.svg"
                    alt="dots"
                    width={18}
                    height={14}
                    className="dots"
                   
                  />
                </td>
              </tr>
              <tr className="align-middle">
                <th scope="row" className="table-border-custom">
                  <input type="checkbox"></input>
                </th>
                <td>2</td>
                <td>Sticky Widget</td>
                <td>All over Web</td>
                <td>My new button</td>
                <td className="status">ON</td>
                <td style={{ fontWeight: 900 }}>124556</td>
                <td>23/11/2020</td>
                <td>
                  <Image
                    src="/assets/dots-vertical.svg"
                    alt="dots"
                    width={18}
                    height={14}
                    className="dots"
                   
                  />
                </td>
              </tr>
              <tr className="align-middle">
                <th scope="row" className="table-border-custom">
                  <input type="checkbox"></input>
                </th>
                <td>3</td>
                <td>Sticky Widget</td>
                <td>All over Web</td>
                <td>My new button</td>
                <td className="status">ON</td>
                <td style={{ fontWeight: 900 }}>124556</td>
                <td>23/11/2020</td>
                <td>
                  <Image
                    src="/assets/dots-vertical.svg"
                    alt="dots"
                    width={18}
                    height={14}
                    className="dots"
                  
                  />
                </td>
              </tr>
              <tr className="align-middle">
                <th scope="row" className="table-border-custom">
                  <input type="checkbox"></input>
                </th>
                <td>4</td>
                <td>Sticky Widget</td>
                <td>All over Web</td>
                <td>My new button</td>
                <td className="status">ON</td>
                <td style={{ fontWeight: 900 }}>124556</td>
                <td>23/11/2020</td>
                <td>
                  <Image
                    src="/assets/dots-vertical.svg"
                    alt="dots"
                    width={18}
                    height={14}
                    className="dots"
                    // style={{ paddingRight: 8 + "px" }}
                  />
                </td>
              </tr>
            </tbody>
          </Table>
        </div>
      </main>
    </div>
  );
}
